name: Test release action

on:
  issues:
    types: [opened]
    

jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
    - uses: niklasmerz/release-notify@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
