name: Test release action

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
    

jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
    - uses: niklasmerz/release-at-vote-stage@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message: 'Test'
